### ISSUE TITLE
Move parsing to handlers?

### ISSUE THREAD

**Issue by hampgoodwin** [abelgoodwin1988/IATA-FINDER#17]
We have a bit of ugly code where we're parsing two different csv's based on two different data structs. Do we want to pull this out into their own handlers, or just leave as is until it gets more complicated (if it gets more complicated?).

https://github.com/abelgoodwin1988/iata-finder/blob/b0caa23b875f43653d9507b361d5b570c2e261c0/pkg/dataservice/dataservice.go#L85-L113

**Comment by JacobSNGoodwin** [comment]
I think this depends on a lot of the other issues and if we have to access them in the dataservice. I think for now it's fine as is.

**Comment by hampgoodwin** [comment]
Agreed.
Closing for now; this would be part of a bigger "spaghootter code cleanup"
